"""add authors and genres

Revision ID: 4181b5fd3f15
Revises: 74154412ac02
Create Date: 2026-02-01 09:04:39.146996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4181b5fd3f15'
down_revision: Union[str, None] = '74154412ac02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adj
    op.create_table(
        'authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'genres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books') as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer()))
        batch_op.add_column(sa.Column('genre_id', sa.Integer()))
        batch_op.create_foreign_key(
            'fk_books_author',
            'authors',
            ['author_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_books_genre',
            'genres',
            ['genre_id'],
            ['id']
        )


def downgrade() -> None:
    with op.batch_alter_table('books') as batch_op:
        batch_op.drop_constraint('fk_books_author', type_='foreignkey')
        batch_op.drop_constraint('fk_books_genre', type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('genre_id')
    op.drop_table('genres')
    op.drop_table('authors')
