"""description

Revision ID: 9f89ff544aa7
Revises: 4181b5fd3f15
Create Date: 2026-02-01 10:22:21.698024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f89ff544aa7'
down_revision: Union[str, None] = '4181b5fd3f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This was originally trying to drop the old 'author' column, but SQLite cannot drop columns easily.
    # You can leave it commented or implement a batch operation if needed.
    # op.drop_column('books', 'author')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adds the 'author' column back if we downgrade
    op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
